# Generated by Django 2.2.2 on 2019-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190630_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Комментарий',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Телефон',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Город',
            new_name='Имя',
        ),
        migrations.DeleteModel(
            name='Улица',
        ),
    ]
